# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=pages.models.media_upload_handler),
        ),
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=pages.models.media_upload_handler),
        ),
    ]
