# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
        ('accounts', '0003_auto_20170711_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='merits',
            field=models.ManyToManyField(blank=True, null=True, to='insights.Merit'),
        ),
    ]
