# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_merits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='merits',
            field=models.ManyToManyField(blank=True, to='insights.Merit'),
        ),
    ]
