# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 22:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('value', models.IntegerField(default=0)),
                ('start', models.DateTimeField()),
                ('duration', models.DurationField(blank=True, null=True)),
                ('end', models.DateTimeField()),
                ('type', models.CharField(choices=[('WDC', 'word clicks'), ('VDC', 'video clicks'), ('ADC', 'audio clicks')], max_length=3)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL)),
                ('book_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design', to='book.BookMedia')),
            ],
        ),
    ]
