# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 16:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Merit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('stage', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='AssetInteraction',
            fields=[
                ('interaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='insights.Interaction')),
                ('type', models.CharField(choices=[('WDC', 'word clicks'), ('VDC', 'video clicks'), ('ADC', 'audio clicks')], max_length=3)),
                ('value', models.IntegerField(default=0)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='book.Asset')),
            ],
            bases=('insights.interaction',),
        ),
        migrations.CreateModel(
            name='TimeInteraction',
            fields=[
                ('interaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='insights.Interaction')),
                ('page_type', models.CharField(choices=[('SPG', 'story page'), ('GPG', 'game page')], max_length=3)),
                ('start', models.DateTimeField()),
                ('duration', models.DurationField(blank=True, null=True)),
                ('end', models.DateTimeField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dwell_times', to='book.BookPage')),
            ],
            bases=('insights.interaction',),
        ),
        migrations.AddField(
            model_name='interaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
