# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 23:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awardance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Merit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('stage', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='awardance',
            name='merit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognitions', to='insights.Merit'),
        ),
        migrations.AddField(
            model_name='awardance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to=settings.AUTH_USER_MODEL),
        ),
    ]
