# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 04:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('author', models.CharField(max_length=256)),
                ('publisher', models.CharField(max_length=256)),
                ('pub_date', models.CharField(max_length=64)),
                ('copyright', models.CharField(max_length=64)),
                ('isbn', models.CharField(max_length=17)),
                ('reading_level', models.CharField(max_length=32)),
                ('word_count', models.CharField(max_length=5)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visual_artist', models.CharField(max_length=256)),
                ('animator', models.CharField(blank=True, max_length=256, null=True)),
                ('composer', models.CharField(blank=True, max_length=256, null=True)),
                ('type', models.CharField(choices=[('BPG', 'pages pages'), ('GPG', 'game pages'), ('DPG', 'dashboard pages')], max_length=3)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('location', models.CharField(max_length=50)),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('content_text', models.TextField(max_length=5000)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('end', models.DateTimeField()),
                ('type', models.CharField(choices=[('WDC', 'word clicks'), ('VDC', 'video clicks'), ('ADC', 'audio clicks')], max_length=3)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
