# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='asset_type',
        ),
        migrations.AddField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('AUD', 'audio'), ('VID', 'video'), ('IMG', 'image'), ('IMA', 'image and audio'), ('TXA', 'text and audio')], default=django.utils.timezone.now, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='bookpage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='book.BookPage'),
        ),
    ]
