# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20170705_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='content_text',
        ),
        migrations.AddField(
            model_name='asset',
            name='text',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
