# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20170622_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=245, null=True)),
                ('is_title_page', models.BooleanField(default=False)),
                ('page_order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='book.Book')),
            ],
        ),
        migrations.RemoveField(
            model_name='bookmedia',
            name='book',
        ),
        migrations.AddField(
            model_name='bookmedia',
            name='bookpage',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='visuals', to='book.BookPage'),
            preserve_default=False,
        ),
    ]
