# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20170619_2057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name_plural': 'media'},
        ),
        migrations.AddField(
            model_name='media',
            name='caption',
            field=models.CharField(blank=True, max_length=62, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('BPG', 'book page'), ('WPG', 'web_page'), ('GPG', 'game_page')], default='WPG', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediaimage',
            name='alt_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='media',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
