# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20170619_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='audio_clicks',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='video_clicks',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='word_clicks',
        ),
        migrations.AddField(
            model_name='interaction',
            name='actor',
            field=models.CharField(default='player gator', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interaction',
            name='type',
            field=models.CharField(choices=[('WDC', 'word clicks'), ('VDC', 'video clicks'), ('ADC', 'audio clicks')], default='word click', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('BPG', 'book page'), ('WPG', 'web page'), ('GPG', 'game page')], max_length=3),
        ),
        migrations.AlterField(
            model_name='mediaimage',
            name='alt_text',
            field=models.TextField(max_length=500),
        ),
    ]
