# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 22:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20170619_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
