# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20170619_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='location',
            field=models.CharField(default='carousel', max_length=50),
            preserve_default=False,
        ),
    ]
